# turn off redundant banner
quarkus.banner.enabled=false

quarkus.http.port=7272
quarkus.application.name=human-resource

# Database configuration
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.driver=org.postgresql.Driver
quarkus.datasource.username=khoango
quarkus.datasource.password=12022002
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/hr

# Hibernate
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
quarkus.hibernate-orm.second-level-caching-enabled=false

# Open API / Swagger UI
quarkus.swagger-ui.always-include=true

# Jakarta JSON Binding
quarkus.jackson.property-naming-strategy=SNAKE_CASE

# Build image
#quarkus.container-image.build=true

# Authentication
quarkus.smallrye-jwt.enabled=true
smallrye.jwt.sign.key.location=privateKey.pem
## JWT
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=company
#quarkus.native.resources.includes=publicKey.pem

# Uncomment for native build only
#quarkus.package.jar.enabled=false


