# turn off redundant banner
quarkus.banner.enabled=false

quarkus.http.host=localhost
quarkus.http.port=7272
quarkus.application.name=human-resource

# Database configuration
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.driver=org.postgresql.Driver
quarkus.datasource.username=khoango
quarkus.datasource.password=12022002
quarkus.datasource.jdbc.url=jdbc:postgresql://127.0.0.1:5432/hr

# Hibernate
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
quarkus.hibernate-orm.second-level-caching-enabled=false

# Open API / Swagger UI
quarkus.swagger-ui.always-include=true

# Jakarta JSON Binding
#quarkus.jackson.property-naming-strategy=SNAKE_CASE

# Build image
quarkus.container-image.build=true
quarkus.container-image.name=human-resource
quarkus.container-image.tag=1.0.0


# Authentication
quarkus.smallrye-jwt.enabled=true
smallrye.jwt.sign.key.location=privateKey.pem
## JWT
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=company
#quarkus.native.resources.includes=publicKey.pem

# Uncomment for native build only
quarkus.package.jar.enabled=false

# Testing
quarkus.http.test-port=8000
quarkus.http.test-ssl-port=8001
quarkus.http.test-timeout=30s

# Cors
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:4200,grpc://localhost:7000,http://localhost:7000
quarkus.log.min-level=DEBUG

# Logging
## File log
quarkus.log.file.enable=true
quarkus.log.file.level=DEBUG
quarkus.log.file.path=human-resource.log
quarkus.log.file.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %h %N[%i] %-5p [%c{3.}] (%t[%t{id}]) %s%e%n
quarkus.log.file.rotation.max-file-size=5M
quarkus.log.file.encoding=UTF-8

## Asynchronous thread for I/O
quarkus.log.file.async=true
quarkus.log.file.rotation.max-backup-index=10
quarkus.log.file.rotation.file-suffix=.yyyy-MM-dd
quarkus.log.file.rotation.rotate-on-boot=false
## Console log
quarkus.log.console.enable=true
quarkus.log.console.format==%d{yyyy-MM-dd HH:mm:ss,SSS} %h %N[%i] %-5p [%c{3.}] (%t[%t{id}]) %s%e%n
quarkus.log.console.level=INFO
quarkus.log.console.async=true
## System log
quarkus.log.syslog.enable=true
quarkus.log.syslog.level=SEVERE
quarkus.log.syslog.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %h %N[%i] %-5p [%c{3.}] (%t[%t{id}]) %s%e%n
quarkus.log.syslog.app-name=human-resource-sys
quarkus.log.syslog.async=true
## Customize log for each category
### Hibernate log
#### Overwrite default logs
quarkus.log.category."org.hibernate".min-level=DEBUG
quarkus.log.category."org.hibernate".level=DEBUG


# Caching caffeine
quarkus.cache.type=caffeine

# gRPC server
quarkus.grpc.server.use-separate-server=false
quarkus.grpc.clients.departmentGrpcService.use-quarkus-grpc-client=true
quarkus.http.insecure-requests=enabled
quarkus.grpc.clients.departmentGrpcService.tls.enabled=false

quarkus.grpc.detailed-errors=true

# Kafka
#%prod.kafka.bootstrap.servers=kafka:9092
#mp.messaging.incoming.prices.connector=smallrye-kafka